### ISSUE TITLE
It cannot compile for me, says it cannot find libgfshare.h

### ISSUE THREAD

**Issue by RoPe93** [ryancdotorg/threshcrypt#1]
when i run make this happens:
make
gcc  -g -pedantic -std=gnu99 -Wall -Wextra -funsigned-char -Wno-pointer-sign -c main.c -o main.o
main.c:22:24: fatal error: libgfshare.h: No such file or directory
 #include <libgfshare.h>
                        ^
compilation terminated.
Makefile:7: recipe for target 'main.o' failed
make: **\* [main.o] Error 1

Any suggestions, what I did wrong, where is libgfshare.h, I couldnt find it my salf.

**Comment by ryancdotorg** [comment]
You need to have libgfshare and libtomcrypt installed, with the development files. On Debian or Ubuntu

```
sudo apt-get install libgfshare-dev libtomcrypt-dev
```

should be sufficient.

If you're using another distro, the packages are probably available but the names may be different. Platforms other than Linux are totally untested.

**Comment by RoPe93** [comment]
Thanks that solves the problem.
Thanks A LOT man, for the program.
respect.

**Comment by ryancdotorg** [comment]
You need to have the libgfshare and libtomcrypt development packages installed. On Debian or Ubuntu 

```
sudo apt-get install libgfshare-dev libtomcrypt-dev
```

should do.

On January 21, 2015 3:17:47 AM PST, RoPe93 notifications@github.com wrote:

> when i run make this happens:
> make
> gcc  -g -pedantic -std=gnu99 -Wall -Wextra -funsigned-char
> -Wno-pointer-sign -c main.c -o main.o
> main.c:22:24: fatal error: libgfshare.h: No such file or directory
> #include <libgfshare.h>
>                        ^
> compilation terminated.
> Makefile:7: recipe for target 'main.o' failed
> make: **\* [main.o] Error 1
> 
> Any suggestions, what I did wrong, where is libgfshare.h, I couldnt
> find it my salf.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/ryancdotorg/threshcrypt/issues/1

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.
